data_file = "src/chains.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Branan"
public_key = "b05a7b31c26064a9f9234e990fe0b0ecf9a57f1102fbee52e28706c897ad5573"

[[chains]]
name = "altair"
rpc_endpoint = "wss://fullnode.altair.centrifuge.io"
color = "#e6007a"

[[chains]]
name = "centrifuge"
rpc_endpoint = "wss://fullnode.parachain.centrifuge.io"
color = "#e6007a"

